### ISSUE TITLE
Building: Create homepage view

### ISSUE THREAD

**Issue by jhaos** [jhaos/EyeMe#1]
## Description

We need to create the landing page from the login. 

https://app.moqups.com/ETUfHhPCG1mesBe5o7texJ6XxzuGhACE/edit/page/ae8fe8eb0

## Task 

- [x] Prototype tracks list view.
- [x] Prototype trackerslist view.
- [x] Prototype track request buttom
- [x] Protoype  get track request buttom
